
GET {{host}}/policies
###

POST {{host}}/policies
{{jsonContentType}}

{
  "policy": {
    "allow": [
      [
        "view",
        "cats"
      ],
      [
        "edit",
        "cats"
      ],
      [
        "delete",
        "cats"
      ]
    ],
    "deny": [
      [
      #   "edit",
      #   "cats"
      # ],
      # [
        "delete",
        "cats"
      ]
    ]
  }
}
###

DELETE {{host}}/policies/replace-this-sentence-with-ADMIN-to-be-validated
# DELETE {{host}}/policies/ADMIN
###
